# Generated by Django 4.2.3 on 2023-07-30 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Livros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livros',
            name='descricao',
            field=models.CharField(default=500, max_length=500, null=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='livros',
            name='imagem',
            field=models.ImageField(upload_to='img'),
        ),
    ]
