# Generated by Django 4.2.3 on 2023-07-30 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Livros', '0003_alter_livros_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filmes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('ano_lancamento', models.IntegerField()),
                ('resumo', models.CharField(max_length=600)),
                ('assistir', models.CharField(max_length=150)),
                ('imagem', models.ImageField(upload_to='images')),
            ],
        ),
    ]
